"""baseline schema

Revision ID: 46f418a33150
Revises: 
Create Date: 2026-07-14 15:41:44.684123+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '46f418a33150'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_config_key'), 'admin_config', ['key'], unique=True)
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('form', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.String(length=64), nullable=True),
    sa.Column('atc_code', sa.String(length=16), nullable=True),
    sa.Column('prescription_required', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_atc_code'), 'medications', ['atc_code'], unique=False)
    op.create_index(op.f('ix_medications_brand_name'), 'medications', ['brand_name'], unique=False)
    op.create_index(op.f('ix_medications_inn_name'), 'medications', ['inn_name'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_month', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
    op.create_table('ranking_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('w_rating', sa.Float(), nullable=False),
    sa.Column('w_distance', sa.Float(), nullable=False),
    sa.Column('w_responsiveness', sa.Float(), nullable=False),
    sa.Column('w_verified', sa.Float(), nullable=False),
    sa.Column('w_recency', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_fr', sa.String(length=128), nullable=False),
    sa.Column('name_ar', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialties_slug'), 'specialties', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('PATIENT', 'DOCTOR', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointment_status'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availabilities_doctor_id'), 'availabilities', ['doctor_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('ref_type', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_doctor_id'), 'credit_ledger', ['doctor_id'], unique=False)
    op.create_geospatial_table('doctor_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('license_no', sa.String(length=64), nullable=False),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('geopoint', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('consultation_fee', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verification_status'), nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('license_no')
    )
    op.create_index(op.f('ix_doctor_profiles_city'), 'doctor_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_referral_code'), 'doctor_profiles', ['referral_code'], unique=True)
    op.create_index(op.f('ix_doctor_profiles_slug'), 'doctor_profiles', ['slug'], unique=True)
    op.create_table('doctor_specialties',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id', 'specialty_id')
    )
    op.create_table('drug_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_id_a', sa.Integer(), nullable=False),
    sa.Column('medication_id_b', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'MODERATE', 'MAJOR', name='interaction_severity'), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['medication_id_a'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_id_b'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_interactions_medication_id_a'), 'drug_interactions', ['medication_id_a'], unique=False)
    op.create_index(op.f('ix_drug_interactions_medication_id_b'), 'drug_interactions', ['medication_id_b'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('national_id', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_patient_profiles_national_id'), 'patient_profiles', ['national_id'], unique=True)
    op.create_table('pharmacy_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('low_threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_stock_medication_id'), 'pharmacy_stock', ['medication_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_stock_pharmacy_id'), 'pharmacy_stock', ['pharmacy_id'], unique=False)
    op.create_table('reputation_scores',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avg_stars', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELLED', name='subscription_status'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_doctor_id'), 'subscriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'PAID', 'VOID', name='invoice_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_doctor_id'), 'invoices', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'PARTIALLY_FULFILLED', 'FULFILLED', 'EXPIRED', 'CANCELLED', name='prescription_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_code'), 'prescriptions', ['code'], unique=True)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_qr_token'), 'prescriptions', ['qr_token'], unique=True)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_doctor_id', sa.Integer(), nullable=False),
    sa.Column('referred_doctor_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REWARDED', 'EXPIRED', name='referral_status'), nullable=False),
    sa.Column('reward_amount', sa.Float(), nullable=True),
    sa.Column('credit_ledger_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_ledger_id'], ['credit_ledger.id'], ),
    sa.ForeignKeyConstraint(['referred_doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_code'), 'referrals', ['code'], unique=False)
    op.create_index(op.f('ix_referrals_referred_doctor_id'), 'referrals', ['referred_doctor_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_doctor_id'), 'referrals', ['referrer_doctor_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('PATIENT_ON_DOCTOR', 'DOCTOR_ON_PATIENT', name='review_direction'), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'FLAGGED', 'REMOVED', name='review_status'), nullable=False),
    sa.Column('reply', sa.String(length=2000), nullable=True),
    sa.Column('reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'appointment_id', 'direction', name='uq_review_author_appointment_direction')
    )
    op.create_index(op.f('ix_reviews_appointment_id'), 'reviews', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_reviews_author_id'), 'reviews', ['author_id'], unique=False)
    op.create_index(op.f('ix_reviews_target_id'), 'reviews', ['target_id'], unique=False)
    op.create_table('dispenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispenses_pharmacy_id'), 'dispenses', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_dispenses_prescription_id'), 'dispenses', ['prescription_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.String(length=128), nullable=False),
    sa.Column('frequency', sa.String(length=128), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    op.create_table('renewal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='renewal_status'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('resulting_prescription_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resulting_prescription_id'], ['prescriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewal_requests_doctor_id'), 'renewal_requests', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_renewal_requests_patient_id'), 'renewal_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_renewal_requests_prescription_id'), 'renewal_requests', ['prescription_id'], unique=False)
    op.create_table('dispense_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispense_id', sa.Integer(), nullable=False),
    sa.Column('prescription_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispense_id'], ['dispenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_item_id'], ['prescription_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispense_items_dispense_id'), 'dispense_items', ['dispense_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispense_items_dispense_id'), table_name='dispense_items')
    op.drop_table('dispense_items')
    op.drop_index(op.f('ix_renewal_requests_prescription_id'), table_name='renewal_requests')
    op.drop_index(op.f('ix_renewal_requests_patient_id'), table_name='renewal_requests')
    op.drop_index(op.f('ix_renewal_requests_doctor_id'), table_name='renewal_requests')
    op.drop_table('renewal_requests')
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_dispenses_prescription_id'), table_name='dispenses')
    op.drop_index(op.f('ix_dispenses_pharmacy_id'), table_name='dispenses')
    op.drop_table('dispenses')
    op.drop_index(op.f('ix_reviews_target_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_author_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_appointment_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_referrals_referrer_doctor_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_doctor_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_code'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_prescriptions_qr_token'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_code'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_doctor_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_doctor_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('reputation_scores')
    op.drop_index(op.f('ix_pharmacy_stock_pharmacy_id'), table_name='pharmacy_stock')
    op.drop_index(op.f('ix_pharmacy_stock_medication_id'), table_name='pharmacy_stock')
    op.drop_table('pharmacy_stock')
    op.drop_index(op.f('ix_patient_profiles_national_id'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_drug_interactions_medication_id_b'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_medication_id_a'), table_name='drug_interactions')
    op.drop_table('drug_interactions')
    op.drop_table('doctor_specialties')
    op.drop_index(op.f('ix_doctor_profiles_slug'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_referral_code'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_city'), table_name='doctor_profiles')
    op.drop_geospatial_table('doctor_profiles')
    op.drop_index(op.f('ix_credit_ledger_doctor_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_availabilities_doctor_id'), table_name='availabilities')
    op.drop_table('availabilities')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_specialties_slug'), table_name='specialties')
    op.drop_table('specialties')
    op.drop_table('ranking_weights')
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_medications_inn_name'), table_name='medications')
    op.drop_index(op.f('ix_medications_brand_name'), table_name='medications')
    op.drop_index(op.f('ix_medications_atc_code'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_admin_config_key'), table_name='admin_config')
    op.drop_table('admin_config')
    # Alembic's drop_table leaves the Postgres ENUM types behind, which breaks a
    # re-upgrade ("type already exists"). Drop them explicitly (tables are gone).
    for _enum in (
        "appointment_status", "interaction_severity", "invoice_status",
        "prescription_status", "referral_status", "renewal_status",
        "review_direction", "review_status", "subscription_status",
        "user_role", "verification_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {_enum}")
    # ### end Alembic commands ###
