"""performance indexes

Revision ID: 883b8a9b2577
Revises: 46f418a33150
Create Date: 2026-07-14 15:48:07.250389+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883b8a9b2577'
down_revision: str | None = '46f418a33150'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_start_at'), 'appointments', ['start_at'], unique=False)
    op.create_geospatial_index('idx_doctor_profiles_geopoint', 'doctor_profiles', ['geopoint'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_doctor_profiles_geopoint', table_name='doctor_profiles', postgresql_using='gist', column_name='geopoint')
    op.drop_index(op.f('ix_appointments_start_at'), table_name='appointments')
    # ### end Alembic commands ###
